config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'balloons#index', as:'home'
  root 'seatmaps#index', as:'home'
  get 'about' => 'pages#about', as:'about'
  get 'about2' => 'pages#about2', as:'about2'
  get 'show' => 'balloons#show'
  get 'new' => 'balloons#new'
  get 'counts' => 'counts#index'
  get 'edit' => 'balloons#edit'
  # added for feature-001
  get 'seatmaps' => 'seatmaps#index'
  # get 'generateSVG' => 'seatmaps#generateSVG'
  
  # added for tests
  post 'balloon_new' =>'balloons#new'
  post 'balloon_edit' =>'balloons#edit'

  # added for feature-002 - calling controller method from linke
  # post 'seatmap_generateSVG' =>'seatmaps#generateSVG'
  # post 'seatmaps/4' =>'seatmaps#generate'
  # post 'generate'=>'seatmaps#generate(.:format)'
  get 'counts/:id/export_svg' => 'counts#export_svg', :as => 'export_svg'
  
  resources :balloons do 
    resources :comments
  end

  resources :counts
  resources :seatmaps

  namespace 'api' do
    namespace 'v1' do
      resources :balloons
      resources :comments
    end
  end

end

app/models/balloon.rb
class Balloon < ApplicationRecord
    validates :title, presence: true, length: {minimum:3}
    has_many :comments, dependent: :delete_all
end

app/controllers/api/v1/balloons_controller.rb
module Api
    module V1
      class BalloonsController < ApplicationController
        skip_before_action :verify_authenticity_token, :only => [:index, :show, :create, :destroy,:update ]
        # return all balloons, ordered by their created_at date
        def index
            @balloons = Balloon.order('created_at DESC');
            render json: {status: 'SUCCESS', message:'Loaded balloons', data:@balloons},status: :ok
        end

        # return a single balloon by it's unique id feild, includes error check for non existant balloon ids
        def show
            begin
                balloon = Balloon.find(params[:id])
            rescue ActiveRecord::RecordNotFound => e
                balloon = nil
            end
            if balloon == nil
                render json: {status: 'ERROR', message:'That Balloon doesnt exist', data:"@Balloon.errors"},status: :unprocessable_entity
            else 
                render json: {status: 'SUCCESS', message:'Loaded balloon', data:balloon},status: :ok
            end
        end 

        # add a new balloon record via a json post
        def create
            balloon = Balloon.new(balloon_params)
            
            if balloon.save
                render json: {status: 'SUCCESS', message:'Saved balloon', data:balloon},status: :ok
            else
                render json: {status: 'ERROR', message:'Balloon not saved', data:balloon.errors},status: :unprocessable_entity
            end
        end
        
        # delete a balloon record via the api, includes error check for non existant balloon ids
        def destroy
            begin
                balloon = Balloon.find(params[:id])
            rescue ActiveRecord::RecordNotFound => e
                balloon = nil
            end
            if balloon == nil
                render json: {status: 'ERROR', message:'Balloon doesnt exist', data:"No Balloon with this id Exists"},status: :ok
            else 
                balloon.destroy
                render json: {status: 'SUCCESS', message:'Deleted balloon', data:balloon},status: :ok
            end
        end
        
        # update a balloon record via the api endpoint, includes error check for non existant balloon ids
        def update
            begin
                balloon = Balloon.find(params[:id])
            rescue ActiveRecord::RecordNotFound => e
                balloon = nil
            end
            
            if balloon != nil && balloon.update_attributes(balloon_params) 
                render json: {status: 'SUCCESS', message:'Updated balloon', data:balloon},status: :ok
            else
                render json: {status: 'ERROR', message:'Balloon not updated', data:"balloon.error - balloon id doesnt exist"},status: :unprocessable_entity
            end
        end

        private
        # defining the allowed parameters that can be passed in an Update or New post 
        def balloon_params
            params.permit(:title, :body)
        end
      end
    end
end
   

app/controllers/balloons_controller.rb
class BalloonsController < ApplicationController
    http_basic_authenticate_with :name=>"don", :password=>"don", except:[:index, :show]
    
    def index
        @title = "index - Balloons"
        @content = "This page displays a listing of all the balloons in our collection"
        @balloons = Balloon.all
    end
    
    def show
        @title = "Show Balloon"
        @content = "This page displays the detail view for the selected balloon"
        @balloon = Balloon.find(params[:id])
    end

    def new 
        @title = "New Balloon"
        @content = "This page enables you to add a new balloon"
        @balloon = Balloon.new
    end
    
    def create
        # render plain: params[:post].inspect
        @balloon = Balloon.new(balloon_params)

        # validation - redirect if form saves successfully, esle redraw the new form
        if @balloon.save()
            redirect_to @balloon
        else
            render 'new'
        end
    end
    
    private def balloon_params
        params.require(:balloon).permit(:title,:body)
    end
    
    def edit 
        @title = "Edit Balloon"
        @content = "This page displays you to Edit the selected balloon"
        @balloon = Balloon.find(params[:id])
    end

    def update
        @balloon = Balloon.find(params[:id])
        if @balloon.update(balloon_params)
            redirect_to @balloon
        else
            render 'edit'
        end
    end

    def destroy
        @balloon = Balloon.find(params[:id])
        @balloon.destroy
        redirect_to balloons_path
    end 

end

app/helpers/balloons_helper.rb
module BalloonsHelper
end

app/views/balloons/edit.html.erb
<div role="main" class="container" style="padding-top: 60px;" >
    <h1><%= @title%></h1
    <p><%= @content%></p>

    <%= form_for :balloon, url: balloon_path(@balloon), method: :patch do |f| %>
        <!-- #check for errors --> 
        <% if @balloon.errors.any? %>
            <% @balloon.errors.full_messages.each do |msg| %>
            <div class="alert alert danger"><%= msg %> </div>
            <% end %> 
        <% end %> 

        <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title,{:class => 'form-control'}) %>
        </p>
        
        <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body,{:class => 'form-control'}) %>
        </p>
        <p>
        <%= f.submit(:class => 'btn btn-primary') %>
        </p>
    <% end %>
</div>

app/views/balloons/index.html.erb
<div class="container" style="padding-top: 60px;">
    <h1><%= @title %></h1>
    <p><%= @content %></p> 
    <div class="well">
        <% @balloons.each do | balloon | %>
            <%= link_to balloon.title, balloon_path(balloon) %><br>
        <% end %>
    </div>
</div>

app/views/balloons/new.html.erb
<div role="main" class="container" style="padding-top: 60px;" >
    <h1><%= @title%></h1
    <p><%= @content%></p>

    <%= form_for :balloon, url: balloons_path do |f| %>
        <!-- #check for errors --> 
        <% if @balloon.errors.any? %>
            <% @balloon.errors.full_messages.each do |msg| %>
            <div class="alert alert danger"><%= msg %> </div>
            <% end %> 
        <% end %> 

        <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title,{:class => 'form-control'}) %>
        </p>
        
        <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body,{:class => 'form-control'}) %>
        </p>
        <p>
        <%= f.submit(:class => 'btn btn-primary') %>
        </p>
    <% end %>
</div>

app/views/balloons/show.html.erb
<div class="container" style="padding-top: 60px;">
    <h1><%= @title%></h1> 
    <p><%= @content%></p>
    <h2><%= @balloon.title%></h2>
    <p><%= @balloon.body%></p>
    <hr>
    
    <%= link_to "Edit", edit_balloon_path(@balloon), :class => 'btn btn-primary' %>

<!-- 
  original = 
 <%= link_to "Delete", balloon_path(@balloon), method: :delete, :class => 'btn btn-danger'%> 
  TRY =  calling destroy VS delete
 <%= link_to 'Delete', balloon_path(@balloon), method: :destroy, :class => 'btn btn-danger'%> 
  TRY = removing btn class and use plain old link, reverting to delete 
   <%= link_to 'Delete', balloon_path(@balloon), method: :delete %> 
  TRY = add confirm to link (vs button)
  <%= link_to 'Delete', balloon_path(@balloon), method: :delete, data: { confirm: 'Are you sure?' } %>
  TRY = remove confirm , change link label to destroy
  <%= link_to 'Destroy', balloon_path(@balloon), method: :delete, data: { confirm: 'Are you sure?' } %>
  modify path as 
  -->

  <%= link_to 'Delete', balloon_path(@balloon), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>


    <%= render 'comments/comments' %>
    <%= render 'comments/form' %> 

    </div>