config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'balloons#index', as:'home'
  root 'seatmaps#index', as:'home'
  get 'about' => 'pages#about', as:'about'
  get 'about2' => 'pages#about2', as:'about2'
  get 'show' => 'balloons#show'
  get 'new' => 'balloons#new'
  get 'counts' => 'counts#index'
  get 'edit' => 'balloons#edit'
  # added for feature-001
  get 'seatmaps' => 'seatmaps#index'
  # get 'generateSVG' => 'seatmaps#generateSVG'
  
  # added for tests
  post 'balloon_new' =>'balloons#new'
  post 'balloon_edit' =>'balloons#edit'

  # added for feature-002 - calling controller method from linke
  # post 'seatmap_generateSVG' =>'seatmaps#generateSVG'
  # post 'seatmaps/4' =>'seatmaps#generate'
  # post 'generate'=>'seatmaps#generate(.:format)'
  get 'counts/:id/export_svg' => 'counts#export_svg', :as => 'export_svg'
  
  resources :balloons do 
    resources :comments
  end

  resources :counts
  resources :seatmaps

  namespace 'api' do
    namespace 'v1' do
      resources :balloons
      resources :comments
    end
  end

end

app/models/seatmap.rb
class Seatmap < ApplicationRecord
end

app/controllers/seatmaps_controller.rb
class SeatmapsController < ApplicationController
    
    def index
        @title = "index - Seat Maps"
        @content = "This page displays a listing of all the seatmaps that are available"
        @seatmaps = Seatmap.all
    end

    def show
        @title = "Show Seat Map"
        @content = "This page displays the detail view for the selected Seat Map"
        @seatmap = Seatmap.find(params[:id])
    end
    def new 
        @title = "New Seat Map"
        @content = "This page enables you to add a new Seat Map"
        @seatmap = Seatmap.new
    end

    def create
        @seatmap = Seatmap.new(seatmap_params)

        # validation - redirect if form saves successfully, esle redraw the new form
        if @seatmap.save()
            redirect_to @seatmap
        else
            render 'new'
        end
    end
    
    private def seatmap_params
        params.require(:seatmap).permit(:title,:description,:rows, :seats )
    end

    def edit 
        @title = "Edit Seat Map"
        @content = "This page enables you to Edit the selected Seat Map"
        @seatmap = Seatmap.find(params[:id])
    end

    def update
        @seatmap = Seatmap.find(params[:id])
        if @seatmap.update(seatmap_params)
            redirect_to @seatmap
        else
            render 'edit'
        end
    end

    def destroy
        @seatmap = Seatmap.find(params[:id])
        @seatmap.destroy
        redirect_to seatmaps_path
    end 

    def generate
        @seatmap = Seatmap.find(params[:id])
        # render json: {status: 'SUCCESS', message:'clicked generateSVG on show', data:@seatmap},status: :ok
    end 

end

app/helpers/seat_maps_helper.rb
module SeatMapsHelper
end

app/views/seatmaps/edit.html.erb
<div role="main" class="container" style="padding-top: 60px;" >
    <h1><%= @title%></h1
    <p><%= @content%></p>

    <%= form_for :seatmap, url: seatmap_path(@seatmap), method: :patch do |f| %>
        <!-- #check for errors --> 
        <% if @seatmap.errors.any? %>
            <% @seatmap.errors.full_messages.each do |msg| %>
            <div class="alert alert danger"><%= msg %> </div>
            <% end %> 
        <% end %> 
        <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title,{:class => 'form-control'}) %>
        </p>
        <p>
        <%= f.label :description %><br>
        <%= f.text_area(:description,{:class => 'form-control'}) %>
        </p>
        <p>
        <%= f.label :rows %><br>
        <%= f.text_field(:rows,{:class => 'form-control'}) %>
        </p>
        <p>
        <%= f.label :seats %><br>
        <%= f.text_field(:seats,{:class => 'form-control'}) %>
        </p>
        <p>
        <%= f.submit(:class => 'btn btn-primary') %>
        </p>
    <% end %>
</div>

app/views/seatmaps/index.html.erb
<div class="container" style="padding-top: 60px;">
    
    <h1><a href="#" data-background ="green"><%= @title %></a></h1>


    <p><%= @content %></p> 
    <div class="well">
        <% @seatmaps.each do | seatmap | %>
            <%= link_to seatmap.title, seatmap_path(seatmap)%><br>
        <% end %>
    </div>
</div>

app/views/seatmaps/new.html.erb
<div role="main" class="container" style="padding-top: 60px;" >
    <h1><%= @title%></h1
    <p><%= @content%></p>

    <%= form_for :seatmap, url: seatmaps_path do |f| %>
        <!-- #check for errors --> 
        <% if @seatmap.errors.any? %>
            <% @seatmap.errors.full_messages.each do |msg| %>
            <div class="alert alert danger"><%= msg %> </div>
            <% end %> 
        <% end %> 

        <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title,{:class => 'form-control'}) %>
        </p>
        
        <p>
        <%= f.label :description %><br>
        <%= f.text_area(:description,{:class => 'form-control'}) %>
        </p>
        
        <p>
        <%= f.label :rows %><br>
        <%= f.text_field(:rows,{:class => 'form-control'}) %>
        </p>


        <p>
        <%= f.label :seats %><br>
        <%= f.text_field(:seats,{:class => 'form-control'}) %>
        </p>

        <p>
        <%= f.submit(:class => 'btn btn-primary') %>
        </p>

    <% end %>
</div>

app/views/seatmaps/show.html.erb
<div class="container" style="padding-top: 60px;">
    <h1><%=@title%></h1> 
    <p><%= @content%></p>
    <h2><%= @seatmap.title%></h2>
    <p><label for='description'>Description:  </label><%= @seatmap.description%></p>
    <p><label for='rows'>Rows: </label><%= @seatmap.rows%></p>
    <p><label for='seats'>Seats: </label><%= @seatmap.seats%></p>
    <hr>
    <%= link_to "Edit", edit_seatmap_path(@seatmap), :class => 'btn btn-primary' %>
    <%= link_to 'Delete', seatmap_path(@seatmap), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
    <%= link_to "Preview SVG", counts_path(:id=> @seatmap.id),  :class => 'btn btn-primary' %>
</div>