config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'balloons#index', as:'home'
  root 'seatmaps#index', as:'home'
  get 'about' => 'pages#about', as:'about'
  get 'about2' => 'pages#about2', as:'about2'
  get 'show' => 'balloons#show'
  get 'new' => 'balloons#new'
  get 'counts' => 'counts#index'
  get 'edit' => 'balloons#edit'
  # added for feature-001
  get 'seatmaps' => 'seatmaps#index'
  # get 'generateSVG' => 'seatmaps#generateSVG'
  
  # added for tests
  post 'balloon_new' =>'balloons#new'
  post 'balloon_edit' =>'balloons#edit'

  # added for feature-002 - calling controller method from linke
  # post 'seatmap_generateSVG' =>'seatmaps#generateSVG'
  # post 'seatmaps/4' =>'seatmaps#generate'
  # post 'generate'=>'seatmaps#generate(.:format)'
  get 'counts/:id/export_svg' => 'counts#export_svg', :as => 'export_svg'
  
  resources :balloons do 
    resources :comments
  end

  resources :counts
  resources :seatmaps

  namespace 'api' do
    namespace 'v1' do
      resources :balloons
      resources :comments
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyTwo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag  'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- adding new css link to bootstrap cdn -->
    <%= stylesheet_link_tag  "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"   %>
    <!-- javascript -->
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track' => true %>   
  </head>

  <body>

  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Seat Maps</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" <%=link_to "Home", home_path %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%=link_to "Create Seat Map", new_seatmap_path %></a>
      </li>
      <!--
      <li class="nav-item">
        <a class="nav-link" <%=link_to "Counts", counts_path %></a> 
        <a class="nav-link" <%=link_to "SeatMaps", seatmaps_path %></a>
      </li>
      -->
      <li class="nav-item">
        <a class="nav-link" <%=link_to "About", about_path %></a>
      </li>
    </ul>

    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    </div>
  </nav>
  

 <%= yield %>
 
  </body>
</html>